### ISSUE TITLE
Act. 3; Cuadro Comparativo del Metodo de Investigación, Emmanuel Marx Salazar González 1Bs

### ISSUE THREAD

**Issue by marxgonzalez29** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-marxgonzalez29#1]
![IMG-20220903-WA0007](https://user-images.githubusercontent.com/112300981/188283803-a12dd4b8-3517-415f-9325-35ab3c300bf2.jpg)

**Comment by Jaczibeth** [comment]
de 20% sacaste un 17%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
